apiVersion: v2
appVersion: 0.2.1
name: exception-recommender
description: A Helm chart for exception-recommender, which creates PolicyExceptionDrafts from Kyverno's PolicyReport results.
home: https://github.com/giantswarm/exception-recommender
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
version: 0.2.1
annotations:
  application.giantswarm.io/team: shield
